# Generated by Django 3.0.3 on 2021-04-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('url', models.URLField(max_length=128)),
                ('phone', models.IntegerField(max_length=254, unique=True)),
            ],
        ),
    ]
